### ISSUE TITLE
REQ - Recipes skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#101]
Skill for food and drink recipes, for when Mycroft whets your appetite :D.

Possible free api's to use:

https://developer.edamam.com/edamam-recipe-api

https://spoonacular.com/food-api

http://food2fork.com/about/api

http://www.recipepuppy.com/about/api/

**Comment by el-tocino** [comment]
See https://github.com/MycroftAI/mycroft-skills/issues/111 for the drink things. I don't think there's a recipe skill yet, though.

**Comment by el-tocino** [comment]
More useful(?) info to someone willing to work on this:

https://opendata.stackexchange.com/questions/4283/open-downloadable-recipe-database

Spoonacular allows 50 requests a day on the free account, but requires account setup, and attribution:
https://spoonacular.com/food-api 

Edamam has apis for both nutrition and recipes, requires account, attribution: 
https://developer.edamam.com/edamam-nutrition-api
https://developer.edamam.com/edamam-recipe-api

Food2fork also has a free api version, requires attribution:
http://food2fork.com/about/api

**Comment by el-tocino** [comment]
https://github.com/MycroftAI/mycroft-skills/pull/258
