### ISSUE TITLE
QuestionsAnswersSkill times out

### ISSUE THREAD

**Issue by trekjunky** [MycroftAI/mycroft-skills#1028]
OpenSuSE 15.1
Mycroft 19.02 rel 12

5th problem so far. I donated good money not to have ANY problems, but I keep find issue after issue. This issue is that when I use the phrase "Who"s ********" replacing ******* with any name, it times out. I use FallBack DuckDcukGo skill, but that doesn't seem to kick in. The only thing that kicks in is the skill QuestionsAnswersSkill and it times out.

**Comment by el-tocino** [comment]
There's always going to be issues.  That's the nature of complex systems.  Donating money helps fix those issues, it does not preclude their occurrence.

**Comment by krisgesling** [comment]
Hi Trekjunky,
I saw that Steve had responded a bit in the chat as well but to keep track of what's happening I thought it would be easier to respond here.

Was there anything useful in `/var/log/mycroft/skills.log`
assuming it is the DuckDuckGo Skill timing out but would be good to confirm.

Also good to check that all Skills are correctly loaded by typing `:skills` into the CLI. Any Skills showing up in red have had an error and aren't loading, it's possible something is missing entirely too.

**Comment by forslund** [comment]
Project is no longer maintained, closing.
