### ISSUE TITLE
Feature request: Intercom

### ISSUE THREAD

**Issue by lcrocker** [MycroftAI/mycroft-skills#1051]
The only mention I can find of an intercom skill is an old unanswered forum question, so I'll make a formal feature request here. I may very well write it myself, unless I hear that someone else is already doing it. But in any case it should be tracked here.

What I envision is being able to say "Hey Mycroft, connect Mom (or 'kitchen' or 'all"...)". Mycroft will say something like "Call from Lee" on the remote unit. If the user there says "Accept call", it then says "Connected" on both units, and then transfers all audio on each of the units to the other until one of the callers uses a "disconnect" word (say, "Thanks, Mycroft"), after which it will say "Disconnected" and go back to normal mode.

Should probably also have some timeouts so that the callee must respond in a reasonable time, and the call itself will be dropped with no conversation for a certain time.

Seems like voice recording skill might be a good starting point (and having an option to record conversations would be good).

**Comment by forslund** [comment]
Project is no longer maintained, closing.
