### ISSUE TITLE
Remove deprecated values from Skills settingsmeta

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-skills#1092]
With the release of 19.08, we have deprecated the Skill name and color values in Skill settings because they are no longer used by the backend. 

There are many Skills that still have these values set and we need help tracking them down and updating them. They can be set in either a `settingsmeta.json` or `settingsmeta.yaml` file.

An example would be the Date and Time Skill. On lines 2 and 3 of this Skills [settingsmeta.json](https://github.com/MycroftAI/skill-date-time/blob/19.08/settingsmeta.json) file, we can delete lines 2 and 3 that define the Skill `name` and `color`.

For each Skill you update, you will need to create a pull request (PR) back to that Skill's repository (not to mycroft-skills). Each of these PR's can count toward your [Hacktoberfest](https://hacktoberfest.digitalocean.com/) goal.

:1st_place_medal: **If this is your first time contributing to open source - welcome and thank you** :tada: 
[This excellent tutorial on how to make your first open source contribution](https://github.com/firstcontributions/first-contributions#first-contributions) is a great way to get started. But if you have any questions, please join us in the [~dev channel of Mycroft Chat](https://chat.mycroft.ai/community/channels/dev) :grinning:

**Comment by Barathwaja** [comment]
Hi @krisgesling , Can I take it up?? 

As per my understanding, some key-value pairs (**_name & color_**) needs to be removed from all the skills which will be located either in _settingsmeta.json_ or _settingsmeta.yaml_ file, am i right?

**Comment by forslund** [comment]
That sounds exactly correct. You'll need to sign a CLA for the skills created by mycroftai so you might want to start to apply for that so the manual processing can be done while you do the work at hand. Go to https://mycroft.ai/cla to start the process :)

**Comment by krisgesling** [comment]
Yeah that's right. Just be sure to only remove the top-level `name`. 

In the [Date-Time Skill example](https://github.com/MycroftAI/skill-date-time/blob/19.08/settingsmeta.json), you can see this on line 2. 
The section name on line 7 however should remain as this provides a title for that section of the settings and will be shown in your Skill settings page.

Feel free to ask questions here if you're unsure at all.

**Comment by Barathwaja** [comment]
@krisgesling Sure Thanks i will take it.

@forslund sure will sign a CLA.

**Comment by Barathwaja** [comment]
@krisgesling please check this if its right or not?
[https://github.com/MycroftAI/skill-weather/pull/95](
https://github.com/MycroftAI/skill-weather/pull/95)

**Comment by krisgesling** [comment]
Looks good to me.

For the CLA there is one manual step in the process, but I'll follow up with the team once the US wake up again.

**Comment by Barathwaja** [comment]
@krisgesling hey there any updates??

**Comment by forslund** [comment]
Project is no longer maintained, closing.
