### ISSUE TITLE
new skill internals-plasma-skill enables users to lockscreen, switchusers and logout

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-skills#11]
This skill integrates Plasma 5 Desktop Internals with Mycroft which enables users to Lock Screen, Switch Users and Logout of the desktop.

Working features:
Lockscreen
Logout
Switch Users

Git Link: https://github.com/AIIX/mycroft-internals-plasma-skill

**Comment by kfezer** [comment]
Added to mycroft-skills
