### ISSUE TITLE
REQ - Cocktail skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#111]
As per discussions on Slack :D. Would be super nice to have :D.

**Comment by marksev1** [comment]
Btotharye is working on it :).

**Comment by btotharye** [comment]
Tracking this skill at https://github.com/Geeked-Out-Solutions/mycroft-cocktail and should have some work done on it this weekend.

**Comment by el-tocino** [comment]
https://github.com/Geeked-Out-Solutions/mycroft-cocktail 
Probably needs some work.
