### ISSUE TITLE
mycroft - deepdreaming skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#12]
https://github.com/JarbasAI/mycroft-deepdream-skill

gets random seed picture from image net, deep dreams on it using batcountry (caffe cudnn and bvlc_googlenet model)

by default uses 2 pictures, one as guide and one as dream source, this is slow but gets much better results than standard dreaming, can be configured to do so, will make it more user firendly and configurable, video dream is in the making

**Comment by kfezer** [comment]
I'm excited to play with this one. Added to mycroft-skills
