### ISSUE TITLE
submit an issue for inclusion in our community repository

### ISSUE THREAD

**Issue by lachendeKatze** [MycroftAI/mycroft-skills#128]
I would like to request my skill be included in the community repository. It may still need some work on documentation, however.
https://github.com/lachendeKatze/skill-iss-location

**Comment by el-tocino** [comment]
You'll need to make a pull request for it.  See https://github.com/MycroftAI/mycroft-skills/pull/152 for what that can involve.

**Comment by btotharye** [comment]
Closing issue please see #152 @lachendeKatze for creating a PR to add this.
