### ISSUE TITLE
Make tagged releases of skills

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mycroft-skills#1324]
In the effort of packaging MyCroft for Alpine Linux, I'd like to request making tagged releases of all the skills developed by the MycroftAI organization.

As far as I understand there currently is a versioning scheme (latest release being 20.02) but the point releases are basically sha's of commits of that branch. For distribution packaging it would be good enough to have e.g. 20.02, but anything will do as long as not every commit is a new release :wink: 
My end goal is to have downloadable archives in a form of `https://github.com/mycroftai/skill-pairing/archive/$pkgver/skils-pairing-$pkgver.tar.gz` for example, where distributions can just update `$pkgver` in their packages.

**Comment by krisgesling** [comment]
Hi Bart, I can see the benefit in this however we would also need to encourage all Skill developers to do the same. 

Some of our developers aren't familiar with Git and use the Mycroft Skills Kit to create and submit their Skills. So if we were to support this, we'd most likely need to automate the tagging within MSK. 

To be honest, I can't see it being the highest priority for us in the short term, but if it's something you or others are willing to pursue then I can't see a reason not to.

**Comment by PureTryOut** [comment]
I've already been asking individual skill developers to tag their releases, and several already have done so.

I don't feel you have to worry about them as Mycroft, it's up to them to make releases and I'm willing to help them where possible.

I'm literally just asking about the official Mycroft skills, let me worry about the third-party developers 😉

**Comment by forslund** [comment]
Project is no longer maintained, closing.
