### ISSUE TITLE
New Skill: CLI-Command-Skill

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/mycroft-skills#1341]
Moved from here: https://github.com/MycroftAI/mycroft-core/issues/2600
```
from mycroft import MycroftSkill, intent_file_handler
import subprocess

class SealEyeCommand(MycroftSkill):
    def __init__(self):
        MycroftSkill.__init__(self)

    @intent_file_handler('command.cli.intent')
    def handle_testa(self, message):
        utterance = message.data.get('utterance')
        if not ' '  in utterance:  
            self.speak('please say your command')
            return True
        commandL = utterance.split(' ', 1)
        #self.log.info("commandList: "+str(commandL))
        command = utterance.split(' ', 1)[1]
        #self.log.info("command: "+str(command))
        process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        output = output.decode('UTF-8')
        self.log.info("Output: "+str(output))
        self.log.info("Error: "+str(error))
        self.speak(str(output))

def create_skill():
    return SealEyeCommand()
```

**Comment by auwsom** [comment]
How would I add custom trigger words such as 'CLI' to the speech recognizer? Is there a way to build simple acryonyms or short words from phonemes as in the hotword PocketSphinx formulation?

**Comment by krisgesling** [comment]
Hey auwsom, the speech-to-text we currently use is Google ([explanation here](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/stt-engine#default-engine)) so there's no way for us to change how these are transcribed unfortunately. 

The work around as you've found is to see what gets transcribed and include those in your intent handler. This does get confusing in the translate platform when people wonder what you are doing with "seal eyes" but until we can get DeepSpeech up to production grade it's a hard limitation.

In terms of submitting Skills, this may be in another thread already but have you seen the docs section on [how to submit Skills to the Marketplace](https://mycroft-ai.gitbook.io/docs/skill-development/marketplace-submission/skills-acceptance-process#1-submitting-your-skill)?

If you don't have the `mycroft-msk` command available, you can manually activate the virtual environment and just run `msk`
```
source ~/mycroft-core/.venv/bin/activate
msk submit /opt/mycroft/skills/your-skill
```

**Comment by auwsom** [comment]
@krisgesling , thanks, that helps.. Im actually using Mimic locally, so I figured there would be a way to customize it. But maybe I shouldnt do that if I plan on using the Android app. It still seems there should be some at least 'hacky' ways to build up from single syllables. Maybe shortening the recognition time (and accuracy) to decrease the pausing between single letters..

Anyway, thanks for the quicky version of how to submit. I expected it to be much more involved.

PS, I mentioned this in another thread, but it would be great to sort the skills in the marketplace by 'popularity'. Maybe on the number of stars in GitHub. This would really help promote useful skills faster and let the undeveloped or old ones stop cluttering the others (which I would worry about when adding too many skills). There was already a suggestion to combine desktop skills into some kind of suite: https://github.com/MycroftAI/mycroft-skills/issues/1343#issuecomment-640286374

**Comment by krisgesling** [comment]
No worries. 

To clarify, Mimic is Text-to-speech, not speech-recognition. 

Agree on Marketplace. We want to add in some different ways to display, popularity would be a great one, and maybe "desktop" needs to be a category?

**Comment by auwsom** [comment]
Re Mimic: Oh, right, it is. So then the offline local mycroft is using Google's DeepSpeech, interesting. So it just uses PocketSphinx (or Precise) for the hotword detection.. DeepSpeech does work really well, but doesnt PocketSphinx do speech rec too?

In the Marketplace, having the categories selectable in the sidebar like GMail labels would be helpful also.

**Comment by forslund** [comment]
Project is no longer maintained, closing.
