### ISSUE TITLE
Easier New Skill Install

### ISSUE THREAD

**Issue by theP13RC3** [MycroftAI/mycroft-skills#137]
It's definitely nice to have MSM as an option to improve the ease of installing skills, but there has to be an even easier way; doing it through voice commands, the main Mycroft site, etc., would make hacking Mycroft much more accessible to those who are less well versed in coding and Linux!

**Comment by forslund** [comment]
Hi, good suggestions. There are plans for a "skill store" on the website but it's still a bit away.

Regarding voice install there is some basic functionality to install skills using voice commands
*hey Mycroft, install movie recommendation*
but there is definitely room for improvement. This will likely be under heavy development during the coming months.

We're happy to receive any contributions: code, ideas, bug reports or just cheer =)

**Comment by penrods** [comment]
This is also related to #133.  Part of the guidelines we are looking at for naming skills includes making sure they can be "pronounced" to allow verbal installs.
