### ISSUE TITLE
REQ: Bluetooth Skill

### ISSUE THREAD

**Issue by confin234** [MycroftAI/mycroft-skills#150]
Can somebody make a Bluetooth skill that allows Mycroft to connect to devices like phones, tablets, laptops, and other speakers to transmit audio?

**Comment by warlockz** [comment]
I will add the Bluetooth Skills to mycroft-skills.

**Comment by KathyReid** [comment]
Hi there @confin234  thanks so much for raising this as a request. 
We've now moved all our our Skill Suggestions / requests to 
https://community.mycroft.ai/c/skill-suggestions
Apologies for the extra work, but could I request that you write up this Skill Suggestion there? 
That way our community is able to vote on it.
Kind regards, 
Kathy
