### ISSUE TITLE
Skill Meta Editor - icon prefix changed in FA 5

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-skills#1538]
**Describe the bug**
The font prefix has changed from a generic "fa" for all icons to "fas" for solid icons and "fab" for brand icons.

The Skill meta editor needs to be updated to use the "fab" prefix if a brand icon is selected.

**To Reproduce**
1. Use the current meta editor
2. Type "linkedin" as your icon name
3. See box indicating failure to load icon.

**Comment by forslund** [comment]
Project is no longer maintained, closing.
