### ISSUE TITLE
Mycroft-weather doesn't seem to upgrade cleanly

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-skills#1557]
Mycroft-weather doesn't seem to upgrade cleanly

Added some additional test verbosity to https://hudson.mycroft.team/blue/organizations/jenkins/mycroft-core/detail/test-xdg-rebase/8/pipeline#step-33-log-156

Edit: this may be something quite a bit older. I've manually tried the latest versions and they all upgrade cleanly...

**Comment by forslund** [comment]
Since this seems to have happened a long time ago and a uncached build of the mycroft-core docker image resolved the issue I'm closing this issue

**Comment by krisgesling** [comment]
This is another example of git not being the best way to distribute software. 

There was once a `refactor` branch and now there's a `refactor/thing` branch. Pain ensues and it is likely to happen to quite a lot of people...
