### ISSUE TITLE
[CI] Docker prunes may clash

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-skills#1599]
**Describe the bug**
If two jenkins jobs attempt to prune docker images at the same time an error will be thrown and one job will appear to fail.

**To Reproduce**
1. Process a large batch of Skills simultaneously and you _might_ hit it.
2. Success message posted to PR, but the job fails with the following error
```
+ docker image prune --all --force --filter label=build=mycroft-skills/PR-1584
Error response from daemon: a prune operation is already running
```

**Possible options**
Either add a new global lock so only 1 job can prune at a time.
Or allow failure of pruning to complete without failing the job?

**Comment by forslund** [comment]
Project is no longer maintained, closing.
