### ISSUE TITLE
REQ: OpenHAB Hub Skill

### ISSUE THREAD

**Issue by confin234** [MycroftAI/mycroft-skills#162]
Maybe we can make a skill that allows the Raspberry Pi or other computer inside a Mycroft device to act as an OpenHab hub, just like it would on a normal setup, except without a screen.

**Comment by el-tocino** [comment]
I believe @btotharye is working on a homeassistant version.  Perhaps that would be close to what you're looking for?

**Comment by btotharye** [comment]
closing duplicate of #48
