### ISSUE TITLE
LLM integration skill

### ISSUE THREAD

**Issue by Gamecubert** [MycroftAI/mycroft-skills#1653]
Large language models are a great way to supplement an offline system with access to basic and sometimes more complex information. I would love to see Mycroft support some 4bit ggml models in the future. Perhaps a warning about content accuracy while offline may be in order on first use while offline as well but with the way ai is advancing this could be extremely useful. Mycroft could also do lots of basic tasks as well like acronyms, story telling, and jokes (to some degree). Starting with llama might be a good idea but other models could get support in the future.

**Comment by el-tocino** [comment]
https://community.mycroft.ai/t/hey-neon-talk-to-chatgpt-mark-ii-voice-assistant-update-may-2023/13629/15
