### ISSUE TITLE
New skill: LLM integration

### ISSUE THREAD

**Issue by rpdelaney** [MycroftAI/mycroft-skills#1655]
**Describe the solution you'd like**
Mycroft can integrate with local LLMs or remote via API.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by mikejgray** [comment]
@rpdelaney Mycroft went out of business almost a year and a half ago, but [OVOS](https://community.openconversational.ai/t/howto-begin-your-open-voice-os-journey-with-the-ovos-installer/14900/10) is a fork that's carrying the torch, and it does have an integration with local LLMs: https://github.com/OpenVoiceOS/skill-ovos-fallback-chatgpt

Check out the first link to get OVOS installed and then you can pip install the fallback skill and give it a try!

**Comment by forslund** [comment]
Project is no longer maintained, closing.
