### ISSUE TITLE
Mycroft "Italiano": Skill-personal can't find template 

### ISSUE THREAD

**Issue by massimo1980** [MycroftAI/mycroft-skills#191]
Hi there,
first of all, congrats for your work! it's awesome!
..and sorry for my poor english!
Ok, i've successfully managed to change language of mycroft.ai into "italiano", added pocketsphinx + lang pack and changed the wakeup word into something else...( actually "Anselmo" )
Everything is working fine, so i moved on my way to tryin to translate also the skills in italian.

in particular for the skill "skill-personal":
at question "who are you" ...there are no issues
but when i ask "when" or "where" this error fire out
( i have just created a subfolder "it-it" with all the translations inside: dialog and vocab directory )
`
15:51:27.786 - mycroft.client.speech.main:handle_wakeword:50 - INFO - Wakeword Detected: ei anselmo
15:51:27.797 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "data": {"session": "1172eb3d-b218-4b2e-991e-b8fbef6d79cc", "utterance": "ei anselmo"}, "context": null}
15:51:27.842 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
15:51:28.673 - mycroft.client.speech.mic:listen:499 - DEBUG - Waiting for wake word...
15:51:29.086 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/stt?lang=it-IT&limit=1 HTTP/1.1" 200 None
15:51:29.495 - mycroft.client.speech.listener:transcribe:144 - DEBUG - STT: dove sei nato
15:51:29.498 - mycroft.client.speech.main:handle_utterance:55 - INFO - Utterance: [u'dove sei nato']
15:51:29.505 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "it-IT", "session": "1172eb3d-b218-4b2e-991e-b8fbef6d79cc", "utterances": ["dove sei nato"]}, "context": null}
15:51:29.514 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "it-IT", "skill_id": 1950168795, "utterances": ["dove sei nato"]}, "context": null}
15:51:29.523 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 1950168795, "result": false}, "context": null}
15:51:29.616 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "it-IT", "skill_id": -1492484506, "utterances": ["dove sei nato"]}, "context": null}
15:51:29.624 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": -1492484506, "result": false}, "context": null}
~~~~e": 1.0, "data": [["dove sei nato", "WhereWereYouBornKeyword"]], "key": "dove sei nato", "match": "dove sei nato"}], "key": "dove sei nato", "match": "dove sei nato"}], "utterance": "dove sei nato"}, "context": {"target": null}}
15:51:29.733 - mycroft.skills.core:wrapper:420 - ERROR - An error occurred while processing a request in PersonalSkill
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/skills/core.py", line 407, in wrapper
handler(message)
File "/opt/mycroft/skills/skill-personal/__init__.py", line 60, in handle_where_were_you_born_intent
self.speak_dialog("where.was.i.born")
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/skills/core.py", line 613, in speak_dialog
self.speak(self.dialog_renderer.render(key, data), expect_response)
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.7-py2.7.egg/mycroft/dialog/__init__.py", line 72, in render
raise NotImplementedError("Template not found: %s" % template_name)
NotImplementedError: Template not found: where.was.i.born
15:51:29.739 - mopidy_skill - INFO - restoring volume
15:51:29.745 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "PersonalSkill.handle_where_were_you_born_intent"}, "context": null}
15:51:29.776 - SKILLS - DEBUG - {"type": "speak", "data": {"expect_response": false, "utterance": "An error occurred while processing a request in PersonalSkill"}, "context": null}
15:51:29.778 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"exception": "Template not found: where.was.i.born", "handler": "PersonalSkill.handle_where_were_you_born_intent"}, "context": null}
15:51:29.781 - SKILLS - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
15:51:29.782 - mopidy_skill - INFO - lowering volume
`

**Comment by MatthewScholefield** [comment]
Hello, sorry for getting back to you this late. This question might be better suited for either [our community forums](https://community.mycroft.ai/) or [the main GitHub page](http://github.com/mycroftai/mycroft-core).

It looks like this could be a capitalization issue. Try changing `lang` in the config to `it-it` (note the lowercase) and make sure you have the file: `skill-personal/dialog/it-it/where.was.i.born.dialog`.

**Comment by raffra** [comment]
Hi Massimo, can you explain me how have you changed the stt language to italiano with Pocketspinx?
