### ISSUE TITLE
mycroft-skills : skill wiki works only with english wikipedia web site.

### ISSUE THREAD

**Issue by yleny-dev** [MycroftAI/mycroft-skills#192]
@jdorleans (skill author) or @augustnmonteiro (comitter)

Hello,

The skill wiki ( https://github.com/MycroftAI/skill-wiki/ ) use the french translations for dialog and vocab files when they are available, but there is a problem.
These french translations are in the folders : skill-wiki/dialog/fr-fr/ , skill-wiki/vocab/fr-fr/, skill-wiki/regex/fr-fr/ .
When I ask "Hey Mycroft, wikipedia Rennes", Mycroft  read the ENGLISH wikipedia page for the city Rennes and not the FRENCH wikipedia page.
Can you fix this problem ?
Maybe modify __init__.py file to add loading for an url.rx file in skill-wiki/regex/en-us where the user can configure the URL for wikipedia website to use, as en.wikipedia.org for english and fr.wikipedia.org for french.

**Comment by el-tocino** [comment]
Looks like this can be set within the skill if the language can be read in the config:
>>> wikipedia.set_lang("fr")

https://pypi.python.org/pypi/wikipedia

I'm not super great at python, but hopefully someone can take a look who is better.

**Comment by el-tocino** [comment]
Turns out there's a PR for a German variation https://github.com/MycroftAI/skill-wiki/pull/1/files

Might be useful to alter for a French variation, however, a more generalized method might be preferable in the long run.

**Comment by JarbasAl** [comment]
https://github.com/JarbasAl/skill-wiki-universal/   <- use google translate to fix your troubles

**Comment by penrods** [comment]
Thanks for bringing this up!  This discussion should be in the skill's repo.  I've created an issue for it over there along with my initial thought on a simple resolution:
https://github.com/MycroftAI/skill-wiki/issues/5
