### ISSUE TITLE
mycroft - leaks skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#23]
sends e-mail to users warning them their e-mail has been leaked, requires leaks service

https://github.com/JarbasAI/leaks-skill

https://github.com/JarbasAI/mycroft----dumped-leaks-finder----service

**Comment by kfezer** [comment]
I'm checking on how we best add skills that require other services. Might just add the skill itself for now.

**Comment by el-tocino** [comment]
Still open?
