### ISSUE TITLE
Weather skill "time zone not found" error message badly formed

### ISSUE THREAD

**Issue by hariedo** [MycroftAI/mycroft-skills#237]
* I'm running a Picroft
* With version 0.9.16 of the Mycroft-core software as of 2018-02-03

* When I say "Hey Mycroft, what time is it in Grand Rapids Michigan", or "Hey Mycroft, what time is it in Michigan", the error message is badly formed.  The main sentence of the response is repeated twice for each utterance, and there are computer-style error messages mixed in.

 **what time is it in grand rapids michigan**                                         
 >> I could not find the timezone for grand rapids michigan
 >> It is None                                                                                                                           
 >> I could not find the timezone for grand rapids michigan                                                                              
 >> An error occurred while processing a request in Time Skill
                                                                           
 **what time is it in michigan**                                                                                                             
 >> I could not find the timezone for michigan                                                                                           
 >> It's None
 >> I could not find the timezone for michigan                                                                                           
 >> An error occurred while processing a request in Time Skill

As a bonus issue, I would spell "time zone" as two words, as Mycroft's default mimic voice pronounces "timezone" as **ta ee meh zoh nee**.

**Comment by el-tocino** [comment]
This sounds possibly like a configuration error. How did you set your locale? Can you see if there's some errors in your logs (/var/log/mycroft-*.log), and not just skills?

**Comment by hariedo** [comment]
I didn't do anything for locale, leaving it with the default en_GB.UTF-8 suite that the Picroft Raspbian Jessie image gives you.  This also leaves the TZ environment variable blank, and /etc/timezone has "Etc/UTC".

The thing is, if I ask "what time is it" then skill-date-time responds correctly for my local time.  It's only when I am asking for time elsewhere that it falls flat.

I tried several other ideas, like "in PDT" or "in Japan" but it can't find any timezone information at all.  I was hoping it would not need the speaker to have some intimate knowledge like "what time is it in Europe/Helsinki" to get the time in Finland, but even that query was not working.

In mycroft-admin-service.log:

```
{'context': None, 'data': {'session': '80edd1e3-d8e1-40aa-a4a9-b8ba6d1fd6cc', 'utterance': 'hey mycroft'}, 'type': 'recognizer_loop:wakeword'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener'}, 'data': {'session': '80edd1e3-d8e1-40aa-a4a9-b8ba6d1fd6cc', 'lang': 'en-US', 'utterances': ['what time is it in arizona']}, 'type': 'recognizer_loop:utterance'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener', 'target': None}, 'data': {'TimeKeyword': 'time', 'target': None, '__tags__': [{'key': 'what', 'from_context': False, 'start_token': 0, 'end_token': 0, 'match': 'what', 'entities': [{'key': 'what', 'match': 'what', 'confidence': 1.0, 'data': [['what', 'Give'], ['what', 'QueryKeyword'], ['what', 'GetKeyword'], ['What', 'Concept'], ['what', 'query'], ['what', 'What']]}]}, {'key': 'time', 'from_context': False, 'start_token': 1, 'end_token': 1, 'match': 'time', 'entities': [{'key': 'time', 'match': 'time', 'confidence': 1.0, 'data': [['time', 'TimeKeyword']]}]}, {'key': 'arizona', 'from_context': False, 'start_token': 5, 'end_token': 5, 'match': 'arizona', 'entities': [{'key': 'arizona', 'match': 'arizona', 'confidence': 0.5, 'data': [['arizona', 'Location']]}]}], 'Location': 'arizona', 'utterance': 'what time is it in arizona', 'confidence': 1.0, 'intent_type': '1017122086:SpeakIntent', 'QueryKeyword': 'what'}, 'type': '1017122086:SpeakIntent'}
{'context': None, 'data': {'handler': 'TimeSkill.handle_speak_intent'}, 'type': 'mycroft.skill.handler.start'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener', 'target': None}, 'data': {'utterance': 'I could not find the timezone for arizona', 'expect_response': False}, 'type': 'speak'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener', 'target': None}, 'data': {'utterance': "It's None", 'expect_response': False}, 'type': 'speak'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener', 'target': None}, 'data': {'utterance': 'I could not find the timezone for arizona', 'expect_response': False}, 'type': 'speak'}
{'context': {'ident': '1518097536.35790551857', 'client_name': 'mycroft_listener', 'target': None}, 'data': {'utterance': 'An error occurred while processing a request in Time Skill', 'expect_response': False}, 'type': 'speak'}
{'context': None, 'data': {'exception': "'NoneType' object is not iterable", 'handler': 'Time Skill'}, 'type': 'mycroft.skill.handler.complete'}
{'context': None, 'data': {'handler': 'Time Skill'}, 'type': 'mycroft.skill.handler.complete'}
```

**Comment by hariedo** [comment]
As of this writing, mycroft has updated itself and does not have a mal-formed response as reported above.

The skill could successfully find times for some prominent cities such as **Tokyo** or **London** or **Phoenix**.

However, it "cannot find the time zone for" states or countries such as **Arizona, Michigan, Eastern Standard, Turkey,** or **Greece**.  It also cannot find cities if they are described within their state or country such as **Phoenix Arizona** or **London England**.

**Comment by penrods** [comment]
I'm closing this Issue.  Please address skill problems to the appropriate Skill repo -- e.g. https://github.com/MycroftAI/skill-date-time
