### ISSUE TITLE
REQ: smartthings skill

### ISSUE THREAD

**Issue by danielsjf** [MycroftAI/mycroft-skills#239]
See also the discussion here: https://github.com/MycroftAI/mycroft-core/issues/182

It would function similar to the home assistant skill. First versions could just trigger some on and off switches. A more advanced version could also report sensor data.

The API documentation is here: http://docs.smartthings.com/en/latest/ref-docs/reference.html

I'm willing to help. I have some Python knowledge, but I've never developed a skill yet.

**Comment by KathyReid** [comment]
Hi there @danielsjf thanks so much for raising this as a request. 
We've now moved all our our Skill Suggestions / requests to 
https://community.mycroft.ai/c/skill-suggestions
Apologies for the extra work, but could I request that you write up this Skill Suggestion there? 
That way our community is able to vote on it.
Kind regards, 
Kathy
