### ISSUE TITLE
mycroft - jarbas diagnostics skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#24]
diagnostics for most of my coded stuff

https://github.com/JarbasAI/mycroft-diagnostics-skill

"requires"
https://github.com/JarbasAI/mycroft---freewill---service
https://github.com/JarbasAI/mycroft----dumped-leaks-finder----service
https://github.com/JarbasAI/mycroft-vision-service
https://github.com/JarbasAI/mycroft-deepdream-skill
https://github.com/JarbasAI/mycroft-poetry-skill
https://github.com/JarbasAI/mycroft-facebook-skill
https://github.com/the7erm/mycroft-skill-diagnostics

**Comment by btotharye** [comment]
where does this issue stand @JarbasAI ?

**Comment by el-tocino** [comment]
Is this still an open issue?
