### ISSUE TITLE
Not sure if these wiki pages should be public edit

### ISSUE THREAD

**Issue by CreativeCactus** [MycroftAI/mycroft-skills#243]
https://github.com/MycroftAI/mycroft-skills/wiki/SKILL-bioinformatics

**Comment by el-tocino** [comment]
"GitHub Wikis is a simple way to let others contribute content. Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish."

This is a github feature.  As long as it's not abused, not sure it's a problem.  Closing unless you think we should disable the wiki feature.
