### ISSUE TITLE
Skills are not in alphabetical order

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-skills#245]
Skills are not in alphabetical order, general cleanup needed and then we should enforce that it is kept that way before merging new skills

**Comment by btotharye** [comment]
@JarbasAI are you referring to the Availble skills listing in the readme or what part are not in order just so I'm aware and I'll fix it.

**Comment by btotharye** [comment]
#367 Should fix this

**Comment by JarbasAl** [comment]
this is now irrelevant, the user submitted skills were a mess, but since the move to versioned skills we dont need to cleanup backwards, just ensure new skills are added in the correct place
