### ISSUE TITLE
Picroft using Google AIY Voice HAT microphone

### ISSUE THREAD

**Issue by MrApurvMishra** [MycroftAI/mycroft-skills#249]
Can the Google AIY Voice HAT microphone be used with Picroft?

**Comment by forslund** [comment]
Not out of the box as I've understood things (to old kernel). @tjoen has created an image for the google aiy hat. See this thread on the forums: https://community.mycroft.ai/t/mycroft-with-google-aiy-voice-kit-disk-image/2607

Since this is technically not a skills issue I'm closing it.
