### ISSUE TITLE
mycroft-wallpaper skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#27]
Wallpaper Skill:
- download wallpapers from reddit (subreddit configurable, default = wallpapers)
- change wallpaper to a random one
- change wallpaper every X seconds

TO DO:
- have a flag in cycle thread to turn on and off automatic changer
- add intent to change time between pictures and maybe some other configurations
- read api keys from config file
- auto-detect user desktop env, instead of making configurable

skill: https://github.com/JarbasAI/mycroft---wallpaper---skill

**Comment by kfezer** [comment]
Added
