### ISSUE TITLE
Pull Request template typo

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/mycroft-skills#274]
Upon creation of a new PR, the body autopopulated with a nice template. However, the third checkmark item reads: "README.md has been updated with the following:" and then proceeds to show .gitmodule content. I believe this is a typo in the template.

**Comment by vipulgupta2048** [comment]
Hi @KathyReid, can you please tag this as `Hacktoberfest` 
I have submitted a PR to solve this- Refer to #599  

:hatching_chick: # #
