### ISSUE TITLE
Ping Skill 

### ISSUE THREAD

**Issue by nogre** [MycroftAI/mycroft-skills#30]
This skill uses keywords to get either a server's ping time or status. This can be used to check that a server is responding correctly. Alternatively, one can use this to send GET requests to a server to start or stop services. By using the Ping Skill, custom commands can be created for webhook enabled online services.

For instance, saying, *Mycroft: Ping Google* garners a reply of `Pinged in 9.03 milliseconds`.

If a keyword is set to get the server response, then Mycroft will reply, `Server says: OK 200`, or `Bad Gateway 502`, et cetera.

[https://github.com/nogre/ping-skill](https://github.com/nogre/ping-skill)

**Comment by kfezer** [comment]
Added
