### ISSUE TITLE
Meta Editor does not reflect revised skill naming format

### ISSUE THREAD

**Issue by jrwarwick** [MycroftAI/mycroft-skills#312]
[Skill template readme.md](https://github.com/MycroftAI/mycroft-skills/blob/master/00__skill_template/README.md)  instructs developers to use the Meta Editor tool at https://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html to generate skill readme.md content. The first field, "Name" does not include recent advice on skill naming format (i.e., https://github.com/MycroftAI/mycroft-skills#4-add-your-skill-as-a-submodule)

**Comment by penrods** [comment]
Are you referring to:
```
When picking a name keep in mind that the installer will match by whole words between the dashes. So if a user says "install speed translator" it will look for all skills in the repo with the words 'speed' AND 'translator'. That means it will find "penrod-nautical-speed-translator" but would not find "abc-nautical-speeds-translator". Make sure the pieces of the name are 'speakable' to allow verbal installs. That means "fubar-v2timer" would be a bad name since you can't speak "v2timer" as a word. A better name would be "fubar-timer-v2" or "fubar-timer-version-2".
```

These are currently two related by slightly different "name" fields.  The name in the README is (for now) just for documentation purposes.  The name in the above instructions is the most important one as-of today as it is what actually gets used by the installation skill.

In the next few iterations of the installation system, the submodule name will probably become autogenerated based on the README value, etc. and the contents of the repo in general will become less important as we create an online interface outside of Github.  But that is still at least months out.

**Comment by jrwarwick** [comment]
Yes, sir, that was what I was referring to. I was under the mistaken
impression that all three names (i.e., actual repository name, skill name
in readme.md, and git submodule link) were supposed to be exactly the same.

**Comment by el-tocino** [comment]
Still an issue?

**Comment by jrwarwick** [comment]
I don't know, maybe. What is the standard format of a "skill name" ? And the standard format for the corresponding github repository for a skill? As of today, I am still unable to determine what the standard for each of these is, and therefore I cannot say whether metaeditor follows that (unknown) standard. Or maybe it just doesn't matter. But if that is the case, it would be helpful for the skills repository documentation and the official public Mycroft development documentation to state that plainly.

**Comment by penrods** [comment]
The format of the repo name is no longer a big deal with the approach we are using for 18.08 and the Marketplace.  In the near future the verbal install will use the same "name", not the repo name.  So I'm going to close this issue.
