### ISSUE TITLE
Important skills

### ISSUE THREAD

**Issue by Josca** [MycroftAI/mycroft-skills#332]
Hi,
 please, which skills in /opt/mycroft/skills folder are important and should not be removed? I played with this and I removed some of them. Now picroft device seems to be a little bit broken. It has yellow eyes and it shows message "message_updating" on display. I think it's trying to update original skills set up, isn't it?

How can I repair this?

Is it possible to turn off this "skills validation" feature?

I set this in my config:

~~~bash
  "skills": {
    "auto_update": false,
    ...
  },
~~~

But it still seems to try update skills.

Thanks.

**Comment by el-tocino** [comment]
Did you have any other questions about this?

**Comment by Josca** [comment]
Yes. **So which skills are necessary for Mycroft to run corectly (with blue eyes)?** It's important to know that for everyone how tries to localize Mycroft to new language. For example I had to add `cs` folder to skills like [fallback-unknown](https://github.com/MycroftAI/fallback-unknown) etc. But I was doing it by method "trial and error". Thanks.

**Comment by forslund** [comment]
mark-1 (Set's the eye state after skills are finished loading), fallback-unknown (handles missed intents), stop (aborts speech/skills) are the most important ones for basic functionality. I might be forgetting some skills so don't treat this as a complete list.

**Comment by el-tocino** [comment]
closing if no further issue.
