### ISSUE TITLE
NEW - dictation skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#46]
dictation skill:
- writes what user speaks to a text file

skill: https://github.com/JarbasAI/mycroft-dictation-skill

requires the converse method added to skills core, same as parrotskill PR#539

**Comment by kfezer** [comment]
Waiting on 539

**Comment by btotharye** [comment]
@JarbasAI what is the status of this issue?  We should be able to close this now and you can add the skill to the repo.

**Comment by JarbasAI** [comment]
intent parser PR is not merged, so at this state the skills is not yet functional in core

i will update it to use the adapt context and open a PR when ready
