### ISSUE TITLE
REQ - audiobook skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#47]
requesting a skill to search download and play audiobooks

possible sources:

    http://abook.fm
    http://audioknigi.club
    http://www.audioknigi-online.com
    http://mp3tales.info

api:

    https://librivox.org/api/info

**Comment by btotharye** [comment]
Not sure what the ask is here, this can be built into a skill.  Closing for now re-open if there is more questions.
