### ISSUE TITLE
REQ - openhab-skill 

### ISSUE THREAD

**Issue by kfriesth** [MycroftAI/mycroft-skills#48]
A skill to interoperate with openhab would greatly open up the potential user base and also significatly expand  mycroft's  abilities.

**Comment by blackfireburn** [comment]
http://docs.openhab.org/configuration/restdocs.html

**Comment by kfezer** [comment]
This is a good one and one I've been wanting for myself.

**Comment by mortommy** [comment]
Hi,
I have a first working draft version [here](https://github.com/mortommy/skill-openhab)

**Comment by btotharye** [comment]
@mortommy is this skill working if so can you submit it to the main skills repo?

**Comment by mortommy** [comment]
Yes. It is now under [openhab repository](https://github.com/openhab/openhab-mycroft).

**Comment by btotharye** [comment]
@mortommy can you submit it to the skills repo using the instructions here https://github.com/MycroftAI/mycroft-skills#how-to-add-skills-to-the-repo

**Comment by mortommy** [comment]
already done :-)

**Comment by btotharye** [comment]
ok cool closing out this issue then
