### ISSUE TITLE
Mycroft youtube music skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#5]
This skill illustrates a very simple general music player. It works by downloading music files from youtube (1st result, can be tunned) and playing with Cvlc

Its intended to be a cheap way to play anything without any account (eg. spotify) or having a music library on disk

https://github.com/JarbasAI/mycroft-music-skill

**Comment by aatchison** [comment]
Very nice.

**Comment by kfezer** [comment]
Looks fun! Also a great idea.
