### ISSUE TITLE
NEW - Traffic Skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#50]
EDIT: Found this nice skill that does what I wanted (gets the commute time from Google distance matrix api): Seems someone already started doing it (it works  :) ): https://github.com/BongoEADGC6/mycroft-traffic

**Comment by blackfireburn** [comment]
what feedback would you want?. traffic points or just current commute time with traffic included.

**Comment by marksev1** [comment]
I'd be mostly interested in just current commute time with traffic included.

**Comment by marksev1** [comment]
Seems someone already started doing it (I need to test if it works already :) ): https://github.com/BongoEADGC6/mycroft-traffic

**Comment by JarbasAI** [comment]
instead of closed this should be marked as NEW so it could be added to skills-repo

**Comment by kfezer** [comment]
Added
