### ISSUE TITLE
Add a HTML color picker to the meta-generator for README files

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-skills#502]
## User story

As a **Skill Author**, I want the [meta-generator](https://github.com/MycroftAI/mycroft-skills/blob/18.08/meta_editor.html) form to have a HTML color picker so that the icon I choose can easily have a hex color value applied without me having to copy paste it, so that I can more quickly fill in the meta-generator form and have a beautiful looking README file for my Skill

## Acceptance criteria

* Is client-side only, no server-side processing required
* Does **not** require installation of additional libraries ie Bootstrap
* Ideally, the color-picker should be accessible and follow Section 508 / WCAG 2.0 criteria

**Comment by Om-Pandey** [comment]
Do you want to slider implementation .. or what .. please explain

**Comment by penrods** [comment]
If you look at:  https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html and click on the ```Edit``` tab, you will see a spot to change the color from the default of #40dbb0.  Right now you just type a value, either hex code or named value.  It would be nice to have a pop-up / dropdown of some sort that provides several "nice" options and/or a full color palette explorer.

Something along the lines of this is what I was thinking, myself:  https://www.w3schools.com/colors/colors_picker.asp

**Comment by anushreejain98** [comment]
Can I take this up?

**Comment by forslund** [comment]
Go for it!

**Comment by triartleet** [comment]
Please note that the default HTML color picker has not consistent behavior among browsers. Are you interested in having a consistent one (similar look and interaction between browsers, doable through JS plugin) or you just want the HTML and only?

**Comment by penrods** [comment]
I pointed @anushreejain98 at Spectrum.  I think it is a nice balance of visualization and manual access, plus MIT licensed:
http://bgrins.github.io/spectrum/

**Comment by penrods** [comment]
I merged the solution from @rizdaprasetya to address this.  Thank you all!

**Comment by rorkyendo** [comment]
what can i do for you? i'm the beginners in hacktoberfest

**Comment by KathyReid** [comment]
Hi there @rorkyendo! 
You can see the issues we have tagged with #Hacktoberfest at; 
https://github.com/search?l=&q=org%3AMycroftAI+label%3Ahacktoberfest+state%3Aopen&type=Issues
and feel free to join our Hacktoberfest chat at; 
https://chat.mycroft.ai/community/channels/hacktoberfest
