### ISSUE TITLE
Add FontAwesome icon picker to meta-generator

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-skills#503]
## User story

As a **Skill Author**, I want the [meta-generator](https://github.com/MycroftAI/mycroft-skills/blob/18.08/meta_editor.html) form to have a FontAwesome icon picker so I can easily choose an icon for my Skill without having to separately identify icons by searching FontAwesome. 

## Acceptance criteria

* Is client-side only, no server-side processing required
* Does **not** require installation of additional libraries ie Bootstrap
* Ideally, the icon-picker should be accessible and follow Section 508 / WCAG 2.0 criteria

**Comment by tulikavijay** [comment]
Can I pick this up?

**Comment by forslund** [comment]
Go for it!

**Comment by KathyReid** [comment]
Absolutely :-)On 1 Oct. 2018 17:11, Tulika <notifications@github.com> wrote:Can I pick this up?

**Comment by tulikavijay** [comment]
It says no additional libraries, can I use jQuery?

**Comment by penrods** [comment]
The trick about this is that as we use it right now this tool is a one-file solution that we just send users to [directly using rawgit](https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html).  So I avoided external dependencies and made everything inline.  If you can point to a  URL for a library that will reliably be there, I could probably stomach it.

**Comment by rizdaprasetya** [comment]
Anyone is currently working on this? I'm planning to try make a PR within a day or two for this issue, if anyone don't mind?

**Comment by tulikavijay** [comment]
@penrods sure you can work on this

**Comment by SaketKaswa20** [comment]
Can I do this?

**Comment by forslund** [comment]
Project is unmaintained, closing.
