### ISSUE TITLE
REQ - Todo skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#51]
I'd say Remember the milk or Wunderlist would be good candidates.

https://pypi.python.org/pypi/mekk.rtm/1.2.3

oauth would need to be handled some-way on SBC...

**Comment by JarbasAI** [comment]
i would also like a to-do list, but i think that should be handled offline, a simple to-do list skill shouldnt have any dependencies, then services with APIs probably deserve their own skill

**Comment by marksev1** [comment]
So maybe this - https://pypi.python.org/pypi/todopy would be a good start.

2017-03-08 18:18 GMT+01:00 JarbasAI <notifications@github.com>:

**Comment by marksev1** [comment]
Here is another example for todotxt https://github.com/bacardi55/kalliope-todotxt/blob/master/todotxt.py

**Comment by marksev1** [comment]
Update: forslund made one, I'm currently testing it!

**Comment by gerlachry** [comment]
@marksev1 mind if I tried the one your testing as well?  I made a simple one for Todoist, https://github.com/gerlachry/skill-todoist, that I am testing out but am interested in an offline alternative as well.

**Comment by marksev1** [comment]
I think its best that you contact forslund (the author) since Im travelling
at the moment. Oh nice a todoist skill great I will try yours also when I
come home!

**Comment by MrGrymReaper** [comment]
@marksev1 I think using SQLite (or equivalent) might be better as the you can the use the power of SQL to perform some very useful actions. Which when utilised with this skill you can ask Mycroft virtually anything for items on the todo list.

Also some items on the list could be related to one another in someway, especially when you are using Mycroft to help plan a party or other big event.

**Comment by MrGrymReaper** [comment]
@JarbasAI In my opinion, I however think that though a to-do skill really done with a text file may not offer as much potential for search actions. A well designed lightweight SQL based database however offers much more potential however.

**Comment by MrGrymReaper** [comment]
@JarbasAI Using SQLite may add a few dependencies but in return provides a lot of potential power for initial features and future ones.

**Comment by JarbasAI** [comment]
thank you fro your input, i totally agree with using sql for this

**Comment by MrGrymReaper** [comment]
@JarbasAI Would also allow the option if so configured to synchronise for storage or retrieval by other units as a file (using a secure GDPR compliant connection).

**Comment by MrGrymReaper** [comment]
@JarbasAI You have miss-spelled "for" by writing "fro". I think your thanking me for my input, but others may not be able to comprehend; what you have written.

**Comment by el-tocino** [comment]
sqlite might even be overkill.  A core data-storage module might be a better place to implement for sql, perhaps.  See Red alert for more on the gdpr concerns.

**Comment by CarstenAgerskov** [comment]
The first post mentions Remember the Milk: The cows lists already exists, based on that. https://github.com/CarstenAgerskov/skill-the-cows-lists#readme

**Comment by blackfireburn** [comment]
just installed the https://github.com/CarstenAgerskov/skill-the-cows-lists#readme it works perfectly exactly what i was looking for.

**Comment by el-tocino** [comment]
From now, requests should probably be made over on the forum: http://community.mycroft.ai  

And closing this one, since there seems to be an answer!

**Comment by el-tocino** [comment]
From now, requests should probably be made over on the forum: http://community.mycroft.ai  

And closing this one, since there seems to be an answer!

**Comment by el-tocino** [comment]
Skill suggestions: https://community.mycroft.ai/c/skill-suggestions
