### ISSUE TITLE
NEW - feedback skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#56]
https://github.com/JarbasAI/mycroft-feedback-skill

good boy, good job, nice work -> triggers positive feedback intent -> calls feedback method on last active skill

not sure how this one should be handled because it requires changes to core

**Comment by kfezer** [comment]
I'm going to add this for now, but make sure to update it sometime. We're working on services that subscribe to events and cause things to happen.

**Comment by kfezer** [comment]
Added
