### ISSUE TITLE
NEW - RSS skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#60]
EDIT: Forslund coded one very awesome rss_skill: https://github.com/forslund/rss_skill

**Comment by kfezer** [comment]
This is a bit odd as the rss feeds need to be found. Check out the npr-news skill or the daily meditation skill for examples as those rely on rss feeds.

**Comment by marksev1** [comment]
forslund coded a simple one just today :D...no they don't need to be found, urls to the rss feed should be inputed by the user in the config file.

**Comment by marksev1** [comment]
+1 its an awesome skill

**Comment by kfezer** [comment]
Added
