### ISSUE TITLE
Adding SystemSkill

### ISSUE THREAD

**Issue by CloneMMDDCVII** [MycroftAI/mycroft-skills#67]
# SystemSkill

This is a simple skill based on the HelloWorld template that simply shuts down the computer.

Works on
  - OSes that use systemd

## Current state

Working features:
 - reboot
 - shutdow

Known issues:
 - none (for now)

TODO:
 - a cancel method

https://github.com/CloneMMDDCVII/systemSkill-Mycroft-core-Skill-

**Comment by kfezer** [comment]
Added. Nice one.
