### ISSUE TITLE
REQ - Intercom skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#68]
Would be a cool idea I think.

**Comment by JarbasAI** [comment]
like a direct voice channel between mycroft units?

cool for baby monitor mode :)

**Comment by marksev1** [comment]
Yeah this could be cool.

**Comment by marksev1** [comment]
Mumble could be used as a backend for that - https://github.com/rfw/python-mumble

**Comment by friedger** [comment]
Maybe try matrix.org? https://github.com/matrix-org/matrix-python-sdk

**Comment by virtadpt** [comment]
It can certainly be done with XMPP.  I use SleekXMPP for a bot that does something like this (in a different context from Mycroft).

**Comment by jrwarwick** [comment]
I second @virtadpt ; I think XMPP is the way to go. It is mature, it is the "opensource" standard, and it offers a lot of other possibilities besides the direct intercom feature. However, I think perhaps XMPP should be a feature of mycroft-core, and the intercom skill would then use a simplified interface (including JID management) to establish connections.
@virtadpt : how did you achieve jingle connections with SleekXMPP ? [At a glance](https://github.com/fritzy/SleekXMPP/issues/256) it seems like SleekXMPP does not yet have XEP-0166 plugin.

**Comment by KathyReid** [comment]
Hi there @marksev1  thanks so much for raising this as a request. 
We've now moved all our our Skill Suggestions / requests to 
https://community.mycroft.ai/c/skill-suggestions
We do have an Intercom Skill with some basic specs written up here; 
https://community.mycroft.ai/t/communication-intercom-on-local-network/3812
Apologies for the extra work, but could I request that you add additional comments on the Forum?
That way our community is able to vote on it.
Kind regards, 
Kathy
