### ISSUE TITLE
REQ - IMDB skill

### ISSUE THREAD

**Issue by marksev1** [MycroftAI/mycroft-skills#69]
Could be cool.

**Comment by JarbasAI** [comment]
i have a movie recommendation skill that scrap imdb for top movies and suggests them, can request by movie genre too

https://github.com/JarbasAI/mycroft---movie-recommend-skill


what features would you like added?

**Comment by marksev1** [comment]
Yes this is cool :) should i rename to NEW already or just close it?

**Comment by JarbasAI** [comment]
close it, it is already added
