### ISSUE TITLE
New repos for Skills: google-gmail, google-calendar and google-translate

### ISSUE THREAD

**Issue by jcasoft** [MycroftAI/mycroft-skills#7]
New repo for Skills upgraded to new mycroft API.
New repos have been created for those who still use the old backend

Repos for new mycroft backend

google-gmail
https://github.com/jcasoft/GoogleGmailSkill 

google-calendar
https://github.com/jcasoft/GoogleCalendarSkill

google-translate
https://github.com/jcasoft/TranslateSkill

Repos for old mycroft backend

google-gmail  @ a8505f6
https://github.com/jcasoft/GoogleGmail-Skill 

google-calendar  @ 74f4029
https://github.com/jcasoft/GoogleCalendar-Skill

google-translate @ 11881e6
https://github.com/jcasoft/Translate-Skill

**Comment by aatchison** [comment]
Awesome, thanks @jcasoft .

**Comment by kfezer** [comment]
Added to skills.
