### ISSUE TITLE
Amarok Media Player Skill 

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-skills#70]
Description: Play, Pause, Next, Previous, Stop Music/Song local desktop media player integration. This skill integrates Amarok Music Player with Mycroft which enables users to Play Local Music.

Current state:
Working features:
* Play Music
* Pause Music
* Stop Music
* Next Song
* Previous Song

Depends on: Python-pyutil and Python-dbus

Git Link 1: https://github.com/AIIX/mycroft-amarok-player-plasma-skill
Git Link 2: https://cgit.kde.org/plasma-mycroft.git/tree/mycroft/skills/mycroft-amarok-player-plasma-skill?id=081368e4453e45af336ffed802f859513aed0d44

**Comment by kfezer** [comment]
Added
