### ISSUE TITLE
NEW - sentiment analisys skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#72]
i forgot to leave this one here

https://github.com/JarbasAI/mycroft---sentiment-analisys---skill

**Comment by kfezer** [comment]
I've been meaning to comment before, but can you flatten your skill repos? For example, not have them in a subfolder of the repo, but just have the folder structure like so:
Repo:
__init__.py
README.md
vocab
dialog
regex
....

**Comment by kfezer** [comment]
Added
