### ISSUE TITLE
REQ - How to skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#73]
a skill to teach users how to do stuff,

- search wikihow
- get results links
- get title
- get steps
- get detailed steps
- get step pics

https://github.com/JarbasAI/wikihow---scrapper/tree/master

 code is there, just wrap it into a skill

TODO:
- check for missing pics, i just assumed all steps have a pic
- make into a skill

i'm using this for something else, but think it would make a good skill if someone wants to grab it :)

or maybe i make the skill sometime

**Comment by JarbasAl** [comment]
https://github.com/JarbasAl/skill-how-to
