### ISSUE TITLE
NEW - Fox News Skill

### ISSUE THREAD

**Issue by chrison999** [MycroftAI/mycroft-skills#76]
A skill to play the latest news from Fox News.  Based on the npr-news-skill.

https://github.com/chrison999/mycroft-skill-fox-news

**Comment by kfezer** [comment]
I'm adding this regardless of my personal feelings for Fox News......

**Comment by kfezer** [comment]
Added

**Comment by chrison999** [comment]
LOL!  Wuzzamatter, Kfezer, you don't like "fair and balanced" news?  ;)

Thanks for adding the skill.

**Comment by kfezer** [comment]
<iframe src="//giphy.com/embed/l0NwPZ027mabR6Tg4" width="425.6" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/justin-g-eye-roll-bitch-please-contempt-l0NwPZ027mabR6Tg4">via GIPHY</a></p>
