### ISSUE TITLE
REQ - Help Skill

### ISSUE THREAD

**Issue by chrison999** [MycroftAI/mycroft-skills#78]
If Mycroft is going to succeed in the "consumer" market it needs a built-in help facility because 99.99% of the folks that will be using mycroft might not be extremely tech savy.  So, I don't know how easy/hard/feasible it would be to implement this, but here's some use cases that demonstrate what I'm talking about.  Note that I'm using "apps" instead of "skills" because most consumer users will be familiar with that term but there could be a regex that would trigger for either "apps" or "skills.":

1.  Get help:

    User:  "Hey Mycroft, help me"
    Mycroft: "I can help with apps and commands"

2.  Help with which apps are available:

    User:  "Hey Mycroft, help me with apps"
    Mycroft: "I have these available apps:  date and time, weather, wiki" and so forth

3.  Get help for a specific app:

    User:  "Hey Mycroft, what does the weather app do?"
    Mycroft"  "Weather app is a Mycroft skill that retrieves the current or future weather forecast"

    User:  "Hey Mycroft, help me with commands for the weather app"
    Mycroft:  "The commands for weather are 'what is the weather' or 'what is the weather in New York'"

4.  Get more help:

    User:  "Hey, Mycroft, I need technical support"
    Mycroft:  "The website for technical support for me is www.mycroft.ai or the email address
    is support@mycroft.ai."

I'm just brainstorming here but the data for the help skill could be pulled in when Mycroft is started/rebooted by each skill having a help.xml file that might look something like this:

```
<help>
    <name>
        Weather app
    </name>
    <description>
        A Mycroft skill that retrieves the current or future weather forecast
    </description>
    <commands>
        What is the weather?
        What is the weather in New York?
        What is the weather forecast for tomorrow?
    </commands>
    <support>
        <web>
            www.mycroft.ai
        </web>
        <email>
            support@microft.ai
        </email>
        <phone>
        </phone>
    </support>
</help>
```

I hope the above triggers some thinking about having a help skill built into Mycroft.  I welcome comments, suggestions, other ideas, etc.

Chris

P.S.  As a possible enhancement, the help skill could be coded in such a way that there's a 45 to 60 minute wait between the spoken help request and Mycroft's response during which time crappy elevator music plays and every few minutes Mycroft interrupts and says, "Your help request is important to me so please stand by."  (HUGE grin!)

**Comment by chrison999** [comment]
I was pondering about this today and thought the help file could be in json format in which case it would looke something like this:

```{   "Help": {
        "name":    "Enhance Bitcoin Skill",
        "description":    "A Mycroft skill that retrieves various bitcoin statistics",
        "commands": {
            "Asking Price": {
                "command1":    "high bitcoin price",
                "command2":    "highest bitcoin price",
                "command3":    "asking bitcoin price",
                "command4":    "bitcoin ask price",
                "command5":    "bitcoin asking price",
                "command6":    "You can also add a currency such as bitcoin ask price in Pounds"
            },
            "Bid Price": {
                "command1":    "low bitcoin price",
                "command2":    "lowest bitcoin price",
                "command3":    "bitcoin bid price",
                "command4":    "You can also add a currency such as bitcoin bid price in Euros"
            },
            "Last Price": {
                "command1":    "bitcoin price",
                "command2":    "last bitcoin price",
                "command3":    "bitcoin last price",
                "command4":    "current bitcoin price",
                "command5":    "You can also add a currency such as bitcoin price in Yuan"
            },
            "24 Hour Average Price": {
                "command1":    "average bitcoin price",
                "command2":    "bitcoin average price",
                "command3":    "You can also add a currency such as average bitcoin price in Rupees"
            },
            "24 Hour Volume": {
                "command1":    "bitcoin volume",
                "command2":    "volume of bitcoin",
                "command3":    "You can also add a currency such as bitcoin volume in U S A Dollars"
            }
        },
        "support": {
            "email":    "chrison999@yahoo.ca",
            "website":    "www.crazychris.ca/mycroft"
        }
    }
}
```
Thoughts? Comments?  Suggestions to make it better?  Thanks!

**Comment by JarbasAI** [comment]
i like this idea, and i think these files are well structured and could be auto-generated by the skill itself if they dont exist (assume most people are lazy) :)

**Comment by chrison999** [comment]
@JarbasAI Thanks for your comments.  Having Mycroft auto-generate the help.xml (or .json) file would be a bonus, although I have no idea how to program that (being a beginner Python programmer).  While I recognize and agree that most people are lazy, my view is that if a skill developer wants his/her skill to receive the widest use, then taking a few minutes to put together a help.xml or json file isn't too much to ask.  And, if the developer doesn't then that's their problem, not Mycroft's.  As well, there may be developers who don't really care if their skill offers help, for instance those who are just developing for themselves, experimenting with the technology, fleshing out their design, etc.

As for the structure/content, this is an initial proposal that I'm sure could use more work.  For instance, I struggled with the structure of the "commands" section...  is naming keys "command1", "command2", etc. the best way to go, or would some other naming convention better?

Thoughts?

**Comment by JarbasAI** [comment]
Ill participate in the github repo you created, what you said is one more reason to auto-generate basic docs

i make a quick skill for myself, other people may have a use for it, either by changing it to their needs or as is,  if it was a not very important skill i wouldnt lose time creating docs, but if we make auto-generation then every skill has basic help because of a 1 time job

reading the vocab files would allow at least commands to be spoken for all skills

**Comment by JarbasAI** [comment]
Currently being worked on

auto-generated help files currently look like this https://github.com/JarbasAI/mycroft-skill-HelpMe/blob/master/help.json

a few more tweaks and its only making the user interaction itself

**Comment by el-tocino** [comment]
There's a basic help skill here as well.  
https://github.com/btotharye/mycroft-skill-basichelp/tree/1c8cc06315b68171ac922a7c1543c36f39a3ebf5
