### ISSUE TITLE
NEW - Enhanced Bitcoin Skill

### ISSUE THREAD

**Issue by chrison999** [MycroftAI/mycroft-skills#79]
I have greatly enhanced the bitcoin skill written by Red5d so that it now provides full bitcoin statistics for any currency supported by api.bitcoinaverage.com.  See the README.md file for more details.

I welcome any comments/suggestions for fixing any bug, making it better, etc.

https://github.com/chrison999/mycroft-skill-bitcoin-enhanced

**Comment by kfezer** [comment]
It's enhanced! 

Added
