### ISSUE TITLE
new skill , search and display pictures on screen

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#8]
search google images for search term and display

show random picture from image net database, sources can be adjusted

it needs some tuning for easy configuration and better dialog/voc but works :)

saves on disk to create database (for later expansion, deep dream and image recognition skills)

https://github.com/JarbasAI/mycroft-pictureskill

**Comment by kfezer** [comment]
Added to the mycroft-kills directory
