### ISSUE TITLE
new skill krunner-skill enables desktop local file search 

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-skills#9]
This skill integrates Plasma 5 Krunner with Mycroft which enables users to search their local desktop for files, images, recent documents, bookmarks and utilize other krunner plugins. 

Working features:
Search the KDE Plasma 5 Desktop Environment for: Files, Documents, Bookmarks, Recent Documents / Recent Files and Images

Git Link: https://github.com/AIIX/mycroft-krunner-skill

**Comment by kfezer** [comment]
Added to mycroft-skills
