### ISSUE TITLE
REQ- Chromecast skill

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-skills#94]
Looks like this open-source project is a good solve for adding casting support to mycroft. 

https://github.com/muammar/mkchromecast/

Should allow streaming music and videos.

**Comment by kfezer** [comment]
will require via pip:
pychromecast
soco

apt-get install mkchromecast

**Comment by marksev1** [comment]
Might be beneficial if also DLNA support was bundled in this "future" skill.

**Comment by el-tocino** [comment]
https://github.com/eClarity/skill-chromecast
